export type playerModel = {
  attributes: {
    name?: string
    shardID?: string
  }
  id: string
  links?: any
  relationships?: {
    matches?: {
      data?: {
        id?: string
        type?: string
      }
    }
  }
}

export type userModel = {
  pubgid: string
  uid: string
  pubgname: string
}

export type seasonStats = {
  duo: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
  ['duo-fpp']: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
  solo: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
  ['solo-fpp']: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
  squad: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
  ['squad-fpp']: {
    assists: number
    boosts: number
    dBNOs: number
    dailyKills: number
    dailyWins: number
    damageDealt: number
    days: number
    headshotKills: number
    heals: number
    killPoints: number
    kills: number
    longestKill: number
    longestTimeSurvived: number
    losses: number
    maxKillStreaks: number
    mostSurvivalTime: number
    rankPoints: number
    revives: number
    rideDistance: number
    roadKills: number
    roundMostKills: number
    roundsPlayed: number
    suicides: number
    swimDistance: number
    teamKills: number
    timeSurvived: number
    top1numbers: number
    vehicleDestroys: number
    walkDistance: number
    weaponsAcquired: number
    weeklyKills: number
    weeklyWins: number
    winPoints: number
    wins: number
  }
}
